import { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { Grid } from '@mui/material';
import banner from '../../../assets/images/home_banner.jpg';
import PosterImg from '../../../assets/images/Still Image for CEO Video.png';
import BannerVideo from '../../../assets/images/Home2.mp4'
import CeoVideo from '../../../assets/images/CEO Video-Updates.mp4';

const Index = () => {

    const videoRef = useRef();

    useEffect(() => {
        videoRef.current.playbackRate = 0.5;
    }, [])

    return (
        <div>
            {/* <img src={banner} alt='img' width={"100%"} />  */}

            {/* <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} className='main py-5 my-2 '>
                <Grid className='fs-5' item sm={12} md={1} style={{ opacity: "0" }}>hb</Grid>
                <Grid className='fs-5 d-flex justify-content-center wow animate__animated animate__fadeInUp animate__slow' item sm={10} md={10}>
                    <video
                        width="100%"
                        height=""
                        autoPlay
                        loop
                        controls
                        preload
                        ref={videoRef}
                    >
                        <source src={BannerVideo} width={"100%"} autoPlay />
                        <track kind="captions" src="captions.vtt" label="English" />
                        Sorry, your browser doesn't support embedded videos, but don't worry, you can
                        <a href="https://gosustainable.ai/wp-content/uploads/2024/01/Sustainable-Events-Video.mp4">download it</a>
                        and watch it with your favorite video player!
                    </video>
                </Grid>

                <Grid className='fs-5' item sm={12} md={1} style={{ opacity: "0" }}>njk</Grid>

                <Grid className='fs-5 wow animate__animated animate__fadeInLeft animate__slow ' item sm={12} md={6} style={{ textAlign: 'justify' }}>At <strong>Sirat</strong>, we understand the needs and aspirations of organizations' Chief Marketing Officer (CMO) vertical. We recognize the necessity of aligning your activities with a net-zero framework and creating an action plan to achieve your short-, medium-, and long-term goals to reduce the carbon footprint generated from your marketing operations.</Grid>

                <Grid className='fs-5 wow animate__animated animate__fadeInRight animate__slow ' item sm={12} md={6}>We aim to seamlessly integrate Environmental, Social and Governance (ESG) considerations into your organization's CMO strategies by deeply understanding your needs. Our <Link to="/netZero-consulting" style={{ color: "#ffffd9", textDecoration: 'none' }}>ESG advisory services</Link> and user-friendly <Link to="/measure-ghg-emissions" style={{ color: "#ffffd9", textDecoration: 'none' }}> NetZero tool</Link> are designed to measure the carbon footprint generated by your marketing operations, activity by activity.</Grid>
            </Grid> */}

            <div style={{ maxHeight: "700px", overflow: 'hidden', position: "relative" }}>
                <video
                    width="100%"
                    height="100%"
                    autoPlay
                    loop
                    preload
                    ref={videoRef}
                    muted
                // controls
                >
                    <source src={BannerVideo} width={"100%"} autoPlay />
                    <track kind="captions" src="captions.vtt" label="English" />
                    Sorry, your browser doesn't support embedded videos, but don't worry, you can
                    <a href="https://gosustainable.ai/wp-content/uploads/2024/01/Sustainable-Events-Video.mp4">download it</a>
                    and watch it with your favorite video player!
                </video>
                <div style={{ position: 'absolute', right: '40px', bottom: '25px', color: "white", fontSize: '30px', fontWeight: '800' }}>
                    <span>Enabling the <u>path</u> to NetZero</span>
                </div>
            </div>


            <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} className='main py-5 my-2'>
                <Grid className='fs-5 wow animate__animated animate__fadeInLeft animate__slow ' item sm={12} md={6} style={{ textAlign: 'justify' }}>At <strong>Sirāt</strong>, we understand the needs and aspirations of organizations' Chief Marketing Officer (CMO) vertical. We recognize the necessity of aligning your activities with a NetZero framework. We create an action plan to achieve your short-, medium-, and long-term goals to meet your climate goals and enable the <u>path</u> to NetZero.</Grid>

                <Grid className='fs-5 wow animate__animated animate__fadeInRight animate__slow ' item sm={12} md={6} style={{ textAlign: 'justify' }}>We aim to seamlessly integrate Environmental, Social and Governance (ESG) considerations into your organization's CMO strategies by deeply understanding your needs. Our <Link to="/netZero-consulting" style={{ color: "#ffffd9", textDecoration: 'none' }}>NetZero Consulting</Link> and user-friendly <Link to="/measure-ghg-emissions" style={{ color: "#ffffd9", textDecoration: 'none' }}> NetZero Platform</Link> are designed to measure the CO<sub>2</sub> footprint generated from your marketing operations.</Grid>
                <Grid className='fs-5' item sm={12} md={2} style={{ opacity: "0" }}>hb</Grid>
                {/* <img src={banner} alt='img' width={"100%"} />
            <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} className='main py-5 my-2 '>
                <Grid className='fs-5 wow animate__animated animate__fadeInLeft animate__slow ' item sm={12} md={6}>At <strong>Go Sustainable</strong>, we understand the needs and aspirations of organizations’ Chief Marketing Officer (CMO) vertical and its stakeholders. And we recognize the necessity of aligning your activities with a net-zero framework and creating an action plan, to achieve your short-, mid-, and long-term goals to reduce the greenhouse gas (GHG) emissions.</Grid>
                <Grid className='fs-5 wow animate__animated animate__fadeInRight animate__slow ' item sm={12} md={6}>We strive to seamlessly integrate Environmental, Social, and Governance (ESG) considerations into your organization’s strategy through our advisory services. By aligning ESG principles with business objectives, we will support to enhance your brand credibility and contribute to long-term value creation, reinforcing your organization’s position as a socially responsible leader.</Grid>
            </Grid>
            <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 3 }} className='main py-5 my-2'>
                <Grid className='fs-5' item xs={12} sm={2} md={2} /> */}
                <Grid className='fs-5 d-flex justify-content-center wow animate__animated animate__fadeInUp animate__slow' item sm={8} md={8}>
                    <div className='video-responsive' style={{ position: 'relative', paddingTop: "42px" }}>
                        <video
                            controls
                            // src="https://gosustainable.ai/wp-content/uploads/2024/01/Shafeeq-Video.mp4"
                            src={CeoVideo}
                            poster={PosterImg}
                            width="1000"
                            height="550"
                            loop
                        >
                            <track kind="captions" src="captions.vtt" label="English" />
                            Sorry, your browser doesn't support embedded videos, but don't worry, you can
                            <a href="https://gosustainable.ai/wp-content/uploads/2024/01/Shafeeq-Video.mp4">download it</a>
                            and watch it with your favorite video player!
                        </video>
                    </div>
                </Grid>
                <Grid className='fs-5' item xs={12} sm={2} md={2} />
            </Grid>
        </div>
    )
}

export default Index